### ISSUE TITLE
Visit scheduling

### ISSUE THREAD

**Issue by sachsk** [avniproject/saahas#1]
ref doc: https://docs.google.com/spreadsheets/d/1gPwPPVJ3lPGbeX94aKYzomWgkK1vMqU81L7IVC9Jc7g/edit#gid=2133719620&range=A2

**Comment by garimadosar5** [comment]
QA Notes - 
- Stop scheduling visits after end date of project.

**Comment by garimadosar5** [comment]
QA Notes - 2
- If last visits are pending on 31 march and project end date is also 31 march then it is not scheduling visit for 31 march.
Case - project "Alag Karo". quarterly visit should be there for 31 march 22.

- What happens if we cancel a visit.
