### ISSUE TITLE
Report - Saahas

### ISSUE THREAD

**Issue by utkarshavni** [avniproject/saahas#13]
https://docs.google.com/spreadsheets/d/1gPwPPVJ3lPGbeX94aKYzomWgkK1vMqU81L7IVC9Jc7g/edit#gid=1789578648

**Comment by sachsk** [comment]
Note: the report does not count the data which will be filled in the unplanned encounters. The unplanned visits are hidden.
Report 1:- 
https://reporting.avniproject.org/question/2036-primary-impact-indicators

**Comment by sachsk** [comment]
report 2 link :-https://reporting.avniproject.org/question/2037-beneficiaries

**Comment by garimadosar5** [comment]
**QA Notes -** 
- Filters - Year filter should be date filter. It is weekly and quarterly data.
**Primary Impact Indicators**
- These indicators are from all the encounters. So filter should be on date not year. What if user wants data for a quarter?
- First row total is only for five indicators. It is little confusing, maybe we can change the colour.
Or maybe add indicator heading like Visual indicator and health indicators etc.
- Dumpsite reduction is not getting calculated. It is showing 0%. Value is filled for project Alag Karo 2.0. Quarterly visit.
@utkarshavni Confirm the % calculation with client. Not sure if this is the right approach.

**Beneficiaries**
- % are coming more than 100. How is this calculation working?

**Comment by garimadosar5** [comment]
**QA Notes -** 
- Change year filter to date filter in Beneficiary report as well.
- When date filter is applied. % indicators are not showing.
![Screen Shot 2022-01-24 at 2.18.08 PM.png](https://images.zenhubusercontent.com/5d0a151d5af8b352a1b5784b/76bb42f6-c788-4ca2-bb03-0dac6b2eb205)

**Comment by garimadosar5** [comment]
For @utkarshavni 
Report Beneficiary,  Confirm the % calculation. Not sure if this is the right approach. % is more than 100%. It cannot be data issue as in all the % question, High absolute is defined as 100.

**Comment by utkarshavni** [comment]
Have communicated queries to Veerendra. Waiting for response.

**Comment by garimadosar5** [comment]
Moving this to deploy ready. Client will test first and then if there are changes, will do.
