### ISSUE TITLE
Multiple scheduled visits for same week in DEA creating confusion for users

### ISSUE THREAD

**Issue by utkarshavni** [avniproject/saahas#19]
![Multiple visits issue.jpeg](https://images.zenhubusercontent.com/61dbee9a6fc777578773b609/315f3ad3-d585-47ec-87fd-2a17d4c609f4)

Users in Saahas are using DEA. For one of the projects, there are multiple entries for a single week (Check 7th Feb week in screenshot).

This is most likely happening as users are modifying previous week's entry and then on saving a new visit for next week is scheduled again - and due to multiple visits being displayed on screen, users are getting confused.

Ticket Reference:
https://avni.freshdesk.com/a/tickets/1694

**Comment by sachsk** [comment]
we have fixed this issue for all visits. so now encounter will not schedule any visit on the edit.
All changes are on UAT
Test cases

- [x] On fresh entry all encounters should schedule  visit
- [x] On edit encounter should not schedule any visit
- [x] Test it on the data entry app
- [x] Test it on the mobile app
