### ISSUE TITLE
[App] Show/Hide Impact Indicators for Special Category Project

### ISSUE THREAD

**Issue by utkarshavni** [avniproject/saahas#20]
For Primary Impact Indicators form, Show/Hide values based on the selected value in Special Category field in Project Registration:

The fields to be shown/hidden are mentioned in the columns "When to show" in Primary impact indicators form:

Sheet link:
https://docs.google.com/spreadsheets/d/1gPwPPVJ3lPGbeX94aKYzomWgkK1vMqU81L7IVC9Jc7g/edit#gid=1368760264

Logic:
1. If Special category is selected as Normal, show the fields as they are showing based on current logic (no changes).
2. If Special category is C & D Waste, then show fields where value for "When to show" column is C & D waste
3. If Special category is Bulky Waste, then show fields where value for "When to show" column is bulky waste.
4. If Special category is E-waste, then show fields where value for "When to show" column is E-waste.
5. If Biogas is selected then show fields where value for "When to show" column is Biogas.

**Comment by AchalaBelokar** [comment]
<img width="728" alt="Screenshot 2022-05-24 at 8 13 01 PM" src="https://user-images.githubusercontent.com/104890488/170063620-977134a1-743b-463a-a973-943bb2f54d2a.png">
Dry waste recycled [Bulky waste] Waste Segregation level is not present..

**Comment by nupoorkhandelwal** [comment]
@AchalaBelokar Please mention form name where the issue is happening

**Comment by AchalaBelokar** [comment]
@nupoorkhandelwal When we select bulky waste as special category.
there is weekly form .which contain dry waste recycled ..
which contain waste segregation level  filed which is not present there.**Fixed this**.

**Comment by AchalaBelokar** [comment]
![Screenshot 2022-05-30 at 4 16 49 PM](https://user-images.githubusercontent.com/104890488/170996725-c99a4538-30c2-4796-891b-27b18bee21b6.png)
when we select C and D as special category  for registration.
under this category  Dry waste sent for co processing  there is field  waste repair  is present according to the requirement  it should be remove there.
Direct beneficiaries there is two field  Total No of beneficieries, Total RWAs serviced should be required there.

**Comment by utkarshavni** [comment]
@AchalaBelokar  @nupoorkhandelwal  Total number of beneficiaries and RWA serviced is visible now for special categories. I have fixed them since these were urgent.
