### ISSUE TITLE
[Report] Changes in Primary Impact Indicators Report

### ISSUE THREAD

**Issue by utkarshavni** [avniproject/saahas#22]
Reference sheet for changes in report: (Rows with changes have been highlighted).
https://docs.google.com/spreadsheets/d/1gPwPPVJ3lPGbeX94aKYzomWgkK1vMqU81L7IVC9Jc7g/edit#gid=1789578648

List of changes:
1. Remove first three rows under Total Waste Influenced and replace them with the rows highlighted and calculate based on the formula in sheet. (Waste Processed Directly, Waste Processed Indirectly and Only Segregation   are currently showing cumulative values for both Dry and Wet waste. This needs to be changed to separate rows for Dry as well as Wet waste. )

2. Remove Waste sent for Co-processing (E-waste) from report and replace them with two rows: 
 - Waste Sent for Co-processing
 - E-waste

Logic and calculation has been provided in the sheet.

**Comment by nupoorkhandelwal** [comment]
https://reporting.avniproject.org/question/2036-primary-impact-indicators
