### ISSUE TITLE
[Report] Add row with label name for each category in Reports.

### ISSUE THREAD

**Issue by utkarshavni** [avniproject/saahas#30]
For all the reports, add a row with Label name above indicators of a same category.

Reports Requirement Sheet:
https://docs.google.com/spreadsheets/d/1nUt4zCucLoNQTC_cqDgbANLSIIQtcs0GQTjip-MTNCo/edit#gid=0

Labels has been written in bold with different color of cell in each report for multiple types of indicators. Currently we are separating these indicators with different color coding. We need to add a label above those indicators to mention the category of indicator as written in sheet.

**Comment by nupoorkhandelwal** [comment]
except report -https://reporting.avniproject.org/question/2037-beneficiaries 
(since there is no req doc for this report)
all other reports are updated.
