### ISSUE TITLE
[Reports] Internal Tracking - Project Report

### ISSUE THREAD

**Issue by utkarshavni** [avniproject/saahas#31]
Motivation:
The user will require to look track different parameters of the Project - running at multiple sites.

Goal: 
The user should be able to see different parameters mentioned in the requirement for filtered project.
Filter for Report - Project

Requirements Sheet for the report:
https://docs.google.com/spreadsheets/d/1nUt4zCucLoNQTC_cqDgbANLSIIQtcs0GQTjip-MTNCo/edit#gid=18915596

Acceptance criteria:
The report should correctly display the parameters based on filtered project.

**Comment by arjunk** [comment]
@utkarshavni requirements are not clear on this and you are supposed to provide clarifications on this.

**Comment by utkarshavni** [comment]
The clarifications were provided and new fields were added in Project Registration as those were not present earlier.
