### ISSUE TITLE
[Saahas support] Formula change for direct beneficiaries

### ISSUE THREAD

**Issue by utkarshavni** [avniproject/saahas#38]
**Ticket reference:**
https://avni.freshdesk.com/a/tickets/2401

**Report name** - Beneficiaries
**Indicator** - Project linked direct beneficiaries
**Existing formula** - (Sum of Total HHs from each weekly encounter of the selected date month and project/4)*5
**New formula** - (Total HH/4)*5  where Total HH to be considered from the weekly encounter which has maximum number of Households. 

i.e. If user selects project "A" and "1 septmber" to "7 september" in date range filter then Total HH should be considered from the September month's weekly encounter which has the most number of Total HHs.

**Comment by nupoorkhandelwal** [comment]
The change is not at all clear, moving this card on hold till the client replies.
