### ISSUE TITLE
Saahas Missing Questions

### ISSUE THREAD

**Issue by arjunk** [avniproject/saahas#41]
The customer is reporting that when we uploaded the UAT bundle to Production, we overwritten a lot of stuff. People from ground are reportingn questions are missing
https://avni.freshdesk.com/a/tickets/2695

We need to 
1. analyse the old prod and new prod. The old prod bundle is attached. 
This bundle can be uploaded into a new org and then excel dump can be taken out for both using SQL query from usefulQueries and then we need to identify what all has been overwritten and 
2. get back those questions into prod  ( and UAT)

**My comparison --
https://docs.google.com/spreadsheets/d/1NjFU3qkFLimDl-8GOgRgikAUtf0JHXyb6cuky9KRfrs/edit#gid=0

There are more form elements in prod org currently than in bundle shared by Taqi. So no way to have any changes back until unless client shares.**

**Comment by Gojo-Taqi** [comment]
[https://app.zenhub.com/files/413453620/042a318a-851f-478b-85a5-bd290a2ea91f/download](https://app.zenhub.com/files/413453620/042a318a-851f-478b-85a5-bd290a2ea91f/download)

**Comment by nupoorkhandelwal** [comment]
Est time - 2hrs
