### ISSUE TITLE
[Saahas Support] Migrating data for existing Projects

### ISSUE THREAD

**Issue by utkarshavni** [avniproject/saahas#42]
Ticket reference:
https://avni.freshdesk.com/a/tickets/2627

Org - Saahas

Form: Impact Indicator - Weekly encounter
Group form questions: - Direct Outreach - Training (Questions shown in screenshot)

- [ ] Migrate data for questions shown below for any of the existing projects - from  Weekly encounter to Monthly encounter (Beneficiaries section in the monthly encounter.)
![Ticket 2627.jpg](https://images.zenhubusercontent.com/61dbee9a6fc777578773b609/aee8b339-2755-457d-b571-d60f4fc4895d)

**Comment by nupoorkhandelwal** [comment]
@Utkarsh moving this card bak in Analysis lane, please mention the logic for migrating data from weekly to monthly in detail. like which weeks data need to be put in which month's encounter or do we need to sum all the weeks data and then add to monthly enc??

**Comment by sachsk** [comment]
We are not migrating the data just added the weekly and monthly data in report
