### ISSUE TITLE
[Saahas] - Change of Formula in report

### ISSUE THREAD

**Issue by utkarshavni** [avniproject/saahas#44]
Ticket#
https://avni.freshdesk.com/a/tickets/2587

Report: **Beneficiaries**
https://reporting.avniproject.org/question/2037-beneficiaries

Indicator for which formula has to change:
"Direct Outreach (volunteering activities, trainings, conferences)"

In the "Impact Indicator - Monthly encounter", under Beneficiaries form element, Total Participants are entered for Training, Workshop and OTHERS section. 

**Update formula:**
Total Participants (Training) + Total Participants (Workshops) + Total Participants (OTHERS)

**Test scenario**:
If a Project and Dates are selected in the filter, it should populate data for that project for the selected dates' month in the indicator.  

Formula also updated in the requirement sheet for reports:
https://docs.google.com/spreadsheets/d/1gPwPPVJ3lPGbeX94aKYzomWgkK1vMqU81L7IVC9Jc7g/edit#gid=1789578648

**Comment by sachsk** [comment]
For existing reports to support the change that we did in monthly form without doing migration, we need to make the following changes in the report.

- We haven’t removed questions from weekly (direct outreach). Need to remove it.
- We have to do a sum of “Total Participants” from weekly and monthly encounters for the calculation of Direct outreach.
concept(35410453-53c1-4952-a022-7c2eaa223b03)Total Participants


New formula: from monthly -->Total Participants (Training) + Total Participants (Workshops) + Total Participants (OTHERS) + Total Participants(from weekly)

- Report affected: Beneficiaries


Estimate: 30 min

**Comment by arjunk** [comment]
@vaijayanthisundaram @sachsk what is the current ETA on this? Original estimate says 30 mins.

**Comment by vaijayanthisundaram** [comment]
As I am working with form elements for the first time,I do not have a definite ETA at this point.

**Comment by vaijayanthisundaram** [comment]
@Dinesh2019  - changes are ready for QA (pls pick report from https://reporting.avniproject.org/question/2605-beneficiaries-wip )

**Comment by Dinesh2019** [comment]
Moving this card to QA Failed only for the below clarification
We need to get clarification for the column Waste Generators(%) to pay user fee is blank do we need to fix this and show the value or do we need to leave it as null or blank? if we do not need to fix this we can close the card

https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbFhZIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--6ec7040ddd228a3a62137dd34f82b424671f85c9/Screenshot%202023-09-26%20at%202.04.07%20PM.png

database:

https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbGpZIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--0c8b06ac47798af398c553375cfe3c8bf422f4f5/Screenshot%202023-09-26%20at%206.20.10%20PM.png

**Comment by vaijayanthisundaram** [comment]
@sachsk , please confirm as this was there before this current change was made.

**Comment by vaijayanthisundaram** [comment]
Updated query to show 0 in case of no value.
