### ISSUE TITLE
[Saahas Support] Add subject summary

### ISSUE THREAD

**Issue by nupoorkhandelwal** [avniproject/saahas#46]
Add Subject Summary rule for subject -Project 

- [x] Display Latest Project End date ( from registration or latest Quarterly visit)
- [x] Project status - whether project is Ongoing or Ended (based on project end date, from registration or latest Quarterly visit)

**Comment by nupoorkhandelwal** [comment]
To get all other relevant/imp fields from Saahas call for Subject summary

**Comment by Dinesh2019** [comment]
Clarification :
1. If we select the end date as Sep 2024 but always it is March 2024
2. if we select the end date as Sep 30 2024 the end date yearly shows as mar 2024
3. Monthly and quarterly dates show the end as Sep 2023

**Comment by Dinesh2019** [comment]
When completing the scheduled visit we are getting the below error for all the scheduled visit
steps to reproduce:
1. login to the app 
2. Search the individual
3. Start the any visit and complete the visit while click on the save the app display the below error

https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaTJHIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--3ce185caae6232532288d854df1a93511f8a8f29/Screen%20Recording%202023-09-11%20at%205.44.14%20PM.mov

**Comment by nupoorkhandelwal** [comment]
card on product board to fix bundle upload issue-



  https://github.com/avniproject/avni-webapp/issues/1045
