### ISSUE TITLE
Save button is not responding or fatal error showing for saahas

### ISSUE THREAD

**Issue by Dinesh2019** [avniproject/saahas#47]
Steps to reproduce:
1.Login to app
2.click on the register
3.click on the project or organisation
4.Complete the form
5.click on save or save and another project

After analysis done by product team : Issue is because Visit schedule rule to schedule 'Impact Indicator - Yearly' is resolving to 'Invalid Date' (also visible in the video around the 30 second mark).
To be retested once rule is fixed.

you can refer to this card : https://github.com/orgs/avniproject/projects/2/views/1?filterQuery=save+button&pane=issue&itemId=47852722

**Comment by Dinesh2019** [comment]
@vedfordev we have to fix this for subject type organisation also

**Comment by vedfordev** [comment]
@Dinesh2019 done. moving to qa ready

**Comment by Dinesh2019** [comment]
@vedfordev need to fix the same  issue for the encounter Board,Governance,Compliance - Annual

**Comment by Dinesh2019** [comment]
Changes need to be move to prod

**Comment by vedfordev** [comment]
@Dinesh2019 moved changes to prod. please close the card once qa done.
