### ISSUE TITLE
[Saahas] Leadership and Partnership - Quarterly form

### ISSUE THREAD

**Issue by garimadosar5** [avniproject/saahas#6]
**Ref Doc -** 
https://docs.google.com/spreadsheets/d/1gPwPPVJ3lPGbeX94aKYzomWgkK1vMqU81L7IVC9Jc7g/edit#gid=2132796517

- This is a general encounter with the name "Leadership and Partnership - Quarterly"
- Schedule this form in each quarter. (On the last day of each quarter.)
- Overdue after 7 days.
- On cancel schedule next visit.

**Comment by garimadosar5** [comment]
**QA Notes -** 
- within page put heading in all capital. **Done**



**For all the forms.**
1. error message is showing in grey instead of red.
2. If user type alphabets in numeric field, is says no value specified instead of please write number or something.
![Screen Shot 2021-11-23 at 9.29.39 AM.png](https://images.zenhubusercontent.com/5d0a151d5af8b352a1b5784b/b269308e-bcec-4860-88e9-a73eb1360734)

**Comment by sachsk** [comment]
It's product bug
