### ISSUE TITLE
[Saahas] App bugs/changes

### ISSUE THREAD

**Issue by garimadosar5** [avniproject/saahas#9]
- error page
**Error message -** 
TypeError: i.isAnswerAlreadyPresent is not a function at isChecked (https://app.avniproject.org/static/js/main.c8020420.chunk.js:1:411528) at https://app.avniproject.org/static/js/main.c8020420.chunk.js:1:377389 at Array.map (<anonymous>) at im (https://app.avniproject.org/static/js/main.c8020420.chunk.js:1:377234) at Xi (https://app.avniproject.org/static/js/2.068853db.chunk.js:1:4351212) at bs (https://app.avniproject.org/static/js/2.068853db.chunk.js:1:4397729) at bu (https://app.avniproject.org/static/js/2.068853db.chunk.js:1:4390366) at yu (https://app.avniproject.org/static/js/2.068853db.chunk.js:1:4390291) at lu (https://app.avniproject.org/static/js/2.068853db.chunk.js:1:4387293) at https://app.avniproject.org/static/js/2.068853db.chunk.js:1:4338483

Steps to reproduce the error - 
1. Go to the home page and choose an existing project. For ex. Alag Karo
2. Choose the tab Profile -> Registration Details.
3. Click o Edit.
4. Make any editions, for example change the Type of Project.
5. Click on Next.

- location dropdown (on the second page of the registration) to be removed. instead, introduce one drop down for states and one one text field for District and Taluka

- All registration and enrolment fields filter to be given on search page.

**Comment by sachsk** [comment]
That error was due to some data missing. voided those projects

**Comment by garimadosar5** [comment]
**QA Notes -** 
- Last point is not done.
- App crashing on search page.
- Complete visit name does not show if visit name is long.
![Screen Shot 2021-12-03 at 5.03.47 PM.png](https://images.zenhubusercontent.com/5d0a151d5af8b352a1b5784b/d7b02194-b95e-46e5-9b66-8a0422f9b1f4)

**Comment by sachsk** [comment]
Add state as the coded answer
Based on the location of the project skip the state district and taluk.
Add state, district and taluk filter
